'solc --version' running
'solc gpt3_5_p7_t2_3.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes --allow-paths .,/content' running
Compilation warnings/errors on gpt3_5_p7_t2_3.sol:
[91mError: Identifier already declared.[0m
  --> gpt3_5_p7_t2_3.sol:31:5:
   |
31 |     function totalSupply() public view override returns (uint256) {
   |     ^ (Relevant source part starts here and spans across multiple lines).
Note: The previous declaration is here:
  --> gpt3_5_p7_t2_3.sol:23:5:
   |
23 |     uint256 public immutable totalSupply;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 582, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 753, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 859, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 96, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 722, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 211, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 633, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 151, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 280, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 586, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Identifier already declared.
  --> gpt3_5_p7_t2_3.sol:31:5:
   |
31 |     function totalSupply() public view override returns (uint256) {
   |     ^ (Relevant source part starts here and spans across multiple lines).
Note: The previous declaration is here:
  --> gpt3_5_p7_t2_3.sol:23:5:
   |
23 |     uint256 public immutable totalSupply;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


